[package]
name = "game"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Marciland/Witch-s-Ascendancy/game"
license-file = "LICENSE"
description = "A game written in rust with vulkan."
keywords = ["gamedev", "vulkan"]
categories = ["rendering", "games"]
readme = "readme.md"

[dependencies]
ecs = { version = "0.1.0", path = "../ecs" }
objects = { version = "0.1.0", path = "../objects" }
ash = { workspace = true, features = ["linked"] }
glam = { workspace = true, features = ["std"] }
winit = { workspace = true, features = ["rwh_06"] }
image = { workspace = true, features = ["png"] }
indexmap = { workspace = true, features = ["std"] }
ash-window = "0.13.0"

[lints.clippy]
correctness = "warn"
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "warn"
cargo = "warn"
multiple_crate_versions = { level = "allow", priority = 1 }
cast_possible_truncation = { level = "allow", priority = 1 }
cast_precision_loss = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
struct_field_names = { level = "allow", priority = 1 }
cast_sign_loss = { level = "allow", priority = 1 }
