pub const TITLE: &str = "Witch's Ascendancy";
pub const ICONPATH: &str = "res/icon.png";
pub const TEXTURE_NOT_FOUND: &str = "res/404.png";
pub const FRAGSHADER: &str = "shaders/frag.spv";
pub const VERTSHADER: &str = "shaders/vert.spv";
pub const FPS: u32 = 60;
pub const FRAMES_IN_FLIGHT: usize = 2;
pub const FULLSCREEN: bool = false;
pub const TEXTURE_TABLE: &str = "res/texture_table.json";
